apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: podinfo
  labels:
    app: podinfo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9898
    protocol: TCP
    name: http
  selector:
    app: podinfo
